// for the popup of signin, signup and forgot-password
export const AUTHENTICATION_POPUP_SHOW = "AUTHENTICATION_POPUP_SHOW";
export const AUTHENTICATION_POPUP_HIDE = "AUTHENTICATION_POPUP_HIDE";

// for the compare courses
export const COMPARE_COURSE_ADD = "COMPARE_COURSE_ADD";
export const COMPARE_COURSE_REMOVE = "COMPARE_COURSE_REMOVE";

//courses
export const REMOVE_ALL_COURSES_FILED = "REMOVE_ALL_COURSES_FILED";

export const COURSE_BASIC_DETAIL_ADD = "COURSE_BASIC_DETAIL_ADD";
export const COURSE_BASIC_DETAIL_ERROR = "COURSE_BASIC_DETAIL_ERROR";
export const COURSE_STUDY_LOAD_ADD = "COURSE_STUDY_LOAD_ADD";
export const COURSE_STUDY_MODE_ADD = "COURSE_STUDY_MODE_ADD";
export const COURSE_DESCRIPTION_ADD = "COURSE_DESCRIPTION_ADD";
export const COURSE_DESCRIPTION_ERROR = "COURSE_DESCRIPTION_ERROR";

export const COURSE_DOMESTICE_FEE_ERROR = "COURSE_DOMESTICE_FEE_ERROR";
export const COURSE_DOMESTICE_FEE_ADD = "COURSE_DOMESTICE_FEE_ADD";

export const COURSE_INTERNATION_FEE_ADD = "COURSE_INTERNATION_FEE_ADD";
export const COURSE_INTERNATION_FEE_ERROR = "COURSE_INTERNATION_FEE_ERROR";

export const COURSE_IELTS_DETAILS_ADD = "COURSE_IELTS_DETAILS_ADD";
export const COURSE_IELTS_DETAILS_ERROR = "COURSE_IELTS_DETAILS_ERROR";

export const COURSE_PTE_DETAILS_ADD = "COURSE_PTE_DETAILS_ADD";
export const COURSE_PTE_DETAILS_ERROR = "COURSE_PTE_DETAILS_ERROR";

export const COURSE_INSTITUTE_ADD = "COURSE_INSTITUTE_ADD";
export const COURSE_INSTITUTE_ERROR = "COURSE_INSTITUTE_ERROR";

export const COURSE_CATEGORY_ADD = "COURSE_CATEGORY_ADD";
export const COURSE_CATEGORY_ERROR = "COURSE_CATEGORY_ERROR";

export const COURSE_IMAGE_ADD = "COURSE_IMAGE_ADD";
export const COURSE_DATA = "COURSE_DATA";
//institute
export const REMOVE_ALL_INSTITUTE_FILED = "REMOVE_ALL_INSTITUTE_FILED";
export const BASIC_DETAIL_ADD = "BASIC_DETAIL_ADD";
export const BASIC_DETAIL_ERROR = "BASIC_DETAIL_ERROR";
export const INSTITUTE_RESET = "INSITUTE_RESET";

export const FACILITY_ADD = "FACILITY_ADD";
export const FACILITY_REMOVE = "FACILITY_REMOVE";
export const FACILITY_UPDATE = "FACILITY_UPDATE";
export const FACILITY_ERROR = "FACILITY_ERROR";

export const AWARD_ADD = "AWARD_ADD";
export const AWARD_REMOVE = "AWARD_REMOVE";
export const AWARD_UPDATE = "AWARD_UPDATE";
export const AWARD_ERROR = "AWARD_ERROR";

export const DOCUMENT_ADD = "DOCUMENT_ADD";
export const DOCUMENT_REMOVE = "DOCUMENT_REMOVE";
export const DOCUMENT_UPDATE = "DOCUMENT_UPDATE";

export const IMAGE_ADD = "IMAGE_ADD";
export const IMAGE_REMOVE = "IMAGE_REMOVE";

export const ADD_DEGREE_LEVEL_BASIC = "ADD_DEGREE_LEVEL_BASIC";
