export const ADD_DEGREE_LEVEL_HOME = "ADD_DEGREE_LEVEL_HOME";
export const ADD_COURSES = "ADD_COURSES";
export const ADD_CITIES = "ADD_CITIES";
export const REMOVE_HOME_COURSES_FILTER = "REMOVE_HOME_COURSES_FILTER";
