export const ADD_STUDENT_DETAILS = "ADD_STUDENT_DETAILS";
export const ADD_STUDENT_DETAILS_ERROR = "ADD_STUDENT_DETAILS_ERROR";

export const ADD_MORE_EDU = "ADD_MORE_EDU";
export const ACADEMIC_UPDATE = "ACADEMIC_UPDATE";
export const ADD_ENGLISH_PRO = "ADD_ENGLISH_PRO";
export const ENGLISH_PRO_UPDATE = "ENGLISH_PRO_UPDATE";
export const EDU_ERROR = "EDU_ERROR";
export const ENGLISH_ERROR = "ENGLISH_ERROR";

export const ADD_STD_DOCS = "ADD_STD_DOCS";
export const REMOVE_STD_DOCS = "REMOVE_STD_DOCS";
export const REMOVE_EDU = "REMOVE_EDU";
export const REMOVE_ENGLISH_PRO = "REMOVE_ENGLISH_PRO";
export const MAKE_EDU_BLANK = "MAKE_EDU_BLANK";
export const MAKE_ENGLISH_PRO = "MAKE_ENGLISH_PRO";
export const ADD_ISFETCHED = "ADD_ISFETCHED";
export const CLEAR_STD_DETAILS = "CLEAR_STD_DETAILS";
