export const inputs = [
  {
    label: "First Name",
    type: "text",
    property: "fname",
    // value: fproperty,
    // vali: error.fproperty,
  },
  {
    label: "Last Name",
    type: "text",
    property: "lname",
    // value: lproperty,
    // vali: error.lproperty,
  },
  {
    label: "Email",
    type: "text",
    property: "email",
    // value: email,
    // vali: error.email,
  },
  {
    label: "Birthday",
    type: "date",
    property: "DOB",
    // value: birthday,
    // vali: error.birthday,
  },
  {
    label: "Gender",
    type: "text",
    property: "gender",
    // value: gender,
    // vali: error.gender,
  },
  {
    label: "Address",
    type: "text",
    property: "address",
    // value: address,
    // vali: error.address,
  },
  {
    label: "Phone",
    type: "Number",
    property: "phone",
    // value: phone,
    // vali: error.phone,
  },
  {
    label: "Passport No:",
    type: "Number",
    property: "passport_no",
    // value: passport,
    // vali: error.passport,
  },
  {
    label: "Nationality",
    type: "text",
    property: "nationality",
    // value: nationality,
    // vali: error.nationality,
  },
  {
    label: "Preferred Country",
    type: "text",
    property: "preferred_country",
    // value: pcountry,
    // vali: error.pcountry,
  },
  {
    label: "Preferred Date",
    type: "date",
    property: "preferred_date",
    // value: pdate,
    // vali: error.pdate,
  },
];
